version: "{build}"

shallow_clone: true

environment:
  matrix:
    - NODEJS_VERSION: "18"
      PLATFORM: x64
    - NODEJS_VERSION: "16"
      PLATFORM: x64

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:NODEJS_VERSION) $env:PLATFORM
  - npm install -g npm@8
  # https://github.com/npm/cli/issues/5856#issuecomment-1317755924
  - npm install -g npm
  - npm ci

test_script:
  - node --version
  - npm --version
  - npm run build --if-present
  - npm test

build: off

matrix:
  fast_finish: true

cache:
  - '%APPDATA%\npm-cache\ -> appveyor.yml,package.json,package-lock.json'
